apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: orders-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: 781013578291.dkr.ecr.us-east-1.amazonaws.com/81117/orders-api:1.0.1
          ports:
            - containerPort: 8000
          #env:
          #  - name: ENV_TYPE
          #    value: minikube
      imagePullSecrets:
        - name: registry-creds-ecr